### ISSUE TITLE
Diagnose eyetracking coordinate issues

### ISSUE THREAD

**Issue by mzettersten** [manybabies/mb2-analysis#106]
Each of these labs have an issue in the distribution or coordinates of their x-coordinate eyetracking data:

- [x] babylabINCC: scale of the eyetracking data (and centered around zero)
- [x] babylabBrookes: Are NAs treated as 0s?
- [x] babylabMPIB: seems to be centered around zero for x and negative for y
- [x] babylabPrinceton: zero-centered? negative y-values too
- [x] babylingOslo: weird binning of data
- [x] CorbitLab: oddly high number of zeros - are NAs being converted to zeros?
- [x] infantcogUBC: oddly high number of zeros - NAs treated as zero?
- [x] kidsdevUniofNewcastle: seems to be centered around zero? negative y values too
- [x] mecdmpihcbs: excess zeros for the x coordinate
- [x] MEyeLab: strange scale, negative x and y values
- [x] SkidLSDLab: excess zeros
- [x] sociocognitivelab: negative x-values and y-values
- [x] tauccd: centered around zero, negative y-values
- [x] unicph: centered around zero, negative y-values
- [x] UIUCinfantlab: centered around zero, negative y-values

**Comment by msschreiner** [comment]
- babylabINCC: wrong scale (all values around 0 -> Lucie will contact lab for px data)
- CorbitLab: toddlers only have gaze point data in MCSnorm -> Lucie will contact lab for px data
