### ISSUE TITLE
Fix eyelink x-y coordinates

### ISSUE THREAD

**Issue by mzettersten** [manybabies/mb2-analysis#109]
In importing eyelink data, we are extracting the pupil coordinates px/ py. INstead, I think we should be extracting the screen gaze coordinates gx, gy 
![Screenshot 2024-04-16 at 1 36 39 PM](https://github.com/manybabies/mb2-analysis/assets/28266548/e6204257-d5c6-4be6-b7f0-862171808b39)

**Comment by alvinwmtan** [comment]
Fixed!!
