### ISSUE TITLE
Add a function to pull metadata from Google Sheets

### ISSUE THREAD

**Issue by alvinwmtan** [manybabies/mb2-analysis#113]
Dataset metadata from the Google Sheets (https://docs.google.com/spreadsheets/d/1CGn-ax1hEEIsF5vMKFiX0daQXe7ykZFZo9dm1ePrhKU/edit#gid=0) is currently manually downloaded and pushed; we should add a function that automatically pulls the most recent version whenever we run the pipeline.

**Comment by msschreiner** [comment]
We decided against pulling the metadata from the google sheet.
