### ISSUE TITLE
diagnose issues with labs with unusual looking score graphs

### ISSUE THREAD

**Issue by mzettersten** [manybabies/mb2-analysis#114]
The profile plots for the following labs look unusual and should be checked for issues:

- [x] affcogUTSC: looks like there might be a small issue with longer than expected t_norm?
- [x] babylabAmsterdam: something up with adults? related to missing data issue?
- [x] babylabPrinceton: something up with t_norm (incorrect scale/ sampling rate? errant trial duration?)
- [x] cclUNIRI
- [x] cogConcordia: some oddness/ extended trials for toddlers
- [x] mpievaCCP: looks like an issue with some later than expected t_norm values
- [x] socallabUCSD: rare overly long t_norm?
- [x] tauccd: something funky going on with toddlers and too long t_norm

**Comment by mzettersten** [comment]
babylabAmsterdam and cclUNIRI now fixed thanks to fixes in the import process

**Comment by alvinwmtan** [comment]
babylabPrinceton and tauccd import updated

**Comment by adriansteffan** [comment]
mpievaCCP fixed (rezeroing had conflicts with the other mpi)

socallabUCSD, affcogUTSC, cogConcordia are all webcam data, so delay (videodownload) and general noise is to be expected
