### ISSUE TITLE
Filtering session errors

### ISSUE THREAD

**Issue by msschreiner** [manybabies/mb2-analysis#117]
There are inconsistencies in labs' reporting of session errors. babylabAmsterdam and babblingOslo report no session errors but have an error number in session_error_info specified. We need to decide what should happen with these 5 toddlers:

- [x] babylingOslo_PUIO_018-toddlers
- [x] babylabAmsterdam_UVA_014-toddlers
- [x] babylabAmsterdam_UVA_018-toddlers
- [x] babylabAmsterdam_UVA_110-toddlers
- [x] babylabAmsterdam_UVA_113-toddlers

**Comment by lucie-zimmer** [comment]
I checked the session_error_info and my suggestion is:
- babylingOslo_PUIO_018-toddlers: early termination -> exclude, change demo data -> session_error: "error" 
- babylabAmsterdam_UVA_014-toddlers: inference by caregiver -> exclude, change demo data -> session_error: "error" 
- babylabAmsterdam_UVA_018-toddlers: participant too young (542 days) -> include? (depends on how strict we want to be with the age exclusion; also, we have to consider that labs may treat too young/old children differently. Some might have included them in their dataset, while others might have indicated a session_error)
- babylabAmsterdam_UVA_110-toddlers: participant to young (541 days) -> include? (see above)
- babylabAmsterdam_UVA_113-toddlers: same bin was used -> include

**Comment by msschreiner** [comment]
Thanks, Lucie. I would also include the toddlers that are slightly too young because they are indeed no session error but should rather be excluded via our age criterion.

I have changed the demo info for the other participants accordingly and did not delete the session_error_notes as these do not affect exclusion.
