### ISSUE TITLE
Incorrect test trials for childdevlabAshoka_41A-adults

### ISSUE THREAD

**Issue by msschreiner** [manybabies/mb2-analysis#118]
Participant childdevlabAshoka_41A-adults has two knowledge test trials. First test trial could be used for analysis but 2nd test trial should be excluded. This participant should also be excluded for MB2P.

**Comment by mzettersten** [comment]
How should we best handle cases like this? Options:
- edit the demographic data/ session error file for the lab directly (would just want to document this)
- create a metadata file with corrections to session errors that we read in to the pipeline

We've done both in ManyBabies projects. I think which is preferable might depend on how common we think this will contine to pop up - my lean would be towards just editing the data directly for now, what do you think?

**Comment by msschreiner** [comment]
My guess is that something like this might not happen again or if so, just a small number of cases. I think that editing the demographic data file rather than creating additional files is the easiest way to deal with cases like this.

**Comment by msschreiner** [comment]
I updated the demographic data for this participant marking the second test trial as error.
