### ISSUE TITLE
check extremal values in SMI 

### ISSUE THREAD

**Issue by mcfrank** [manybabies/mb2-analysis#12]
before averaging eyes, check that coordinates are not at the extreme of screen (e.g., 0, 1600, etc.) as this may be an indicator of missing data for one or both eyes. in the case of missingness or big delta between eyes, data should be handled carefully, e.g. not just naively averaged.

**Comment by mcfrank** [comment]
@yuen-francis

**Comment by mahowak** [comment]
![image](https://user-images.githubusercontent.com/5036450/69175684-0fe33f00-0ab9-11ea-9edc-d7f7fabaccbd.png)
This plot shows the problem: SMI seems to return 0 when data from one eye is missing. So naive averaging does the wrong thing in that case.

**Comment by yuen-francis** [comment]
Made pull request with sanity check plots and filter codes in import.R for UBC and Gottingen. The issue seems to be only SMI, Tobii and Eyelink seems to process their raw data differently and does not have this problem of having two eyes being inconsistent.

**Comment by yuen-francis** [comment]
![plot](https://user-images.githubusercontent.com/52611129/69199985-a3833280-0aee-11ea-8cce-c422a69eb401.png)

here's what the left Y vs right Y plot for Tobii looks like, which suggests that Tobii isn't having the same problem and their internal averaging process is probably reliable
