### ISSUE TITLE
exclusion reporting at the end of 006_exclusions.Rmd needs some clean-up

### ISSUE THREAD

**Issue by mzettersten** [manybabies/mb2-analysis#120]
The exclusion code at the end of 006_exclusions.Rmd contains some residual errors because of changes to when and how data exclusions are applied in the code (e.g. `n_adults_included` is incorrect currently). Need a careful look here when we clean up this code for the paper.

**Comment by msschreiner** [comment]
Yes, exclusions are currently, and hopefully correctly, implemented in the paper.RMD. I haven't updated the code in 006_exclusions as I find it redundant to have it twice in the repository. I would have removed the detailed exclusions in 006_exclusions and only have them in the RMDs (paper and supplement), where they are reported. But I am happy to proceed differently if you think we should also have it at other places.

**Comment by mzettersten** [comment]
As part of the big overhaul to the exclusions process (https://github.com/manybabies/mb2-analysis/commit/e471d383b8d5446cd15b71d4d2269d04cf6112ad and https://github.com/manybabies/mb2-analysis/commit/8b1bf039a70c28bda9cbaa05577b3eda023ebc4a), I also cleaned up the exclusions reporting. We should cross-check this against the paper, but I'll make a separate issue for that.
