### ISSUE TITLE
MAIN ANALYSIS 1: first anticipatory look

### ISSUE THREAD

**Issue by mcfrank** [manybabies/mb2-analysis#17]
compute this binary variable and analyze using an LMER or equivalent:

Something like this: 

`lmer(correct_first_anticipation ~ trial_num + (1|subject) + (1|lab), data = anticipations, family = "binomial")`

**Comment by angelinetsui** [comment]
@angelinetsui - just self-assigning myself for this issue

**Comment by angelinetsui** [comment]
@GalRaz , I need help to make much nicer codes to compute first look. Will email you for more details
