### ISSUE TITLE
Systematic discrepancies between eyelink labs

### ISSUE THREAD

**Issue by yuen-francis** [manybabies/mb2-analysis#25]
![image](https://user-images.githubusercontent.com/52611129/69290859-202d1400-0bb6-11ea-9a74-f9904c9e287c.png)

As illustrated in the scatter plot, it would seem that CEU and Copenhagen have a systematic difference in their gaze distribution. This could be due to either differences in calibration, or perhaps differences in placement of the stimuli. I will dig deeper and see if there are errors in the script that corrects for the difference in screen dimensions (which I think is unlikely because the other types of eyetrackers are corrected without issue.). Maybe contact the two labs and double check that their stimuli was displayed at the centre of the screen and not slightly off?

**Comment by mcfrank** [comment]
Dora Kampis is checking into this.

**Comment by mahowak** [comment]
Interesting. Looking at the animations with all labs, you can see this pattern. CEU looks to be skewed left relative to other labs. Copenhagen looks like it generally fits in with the non-EyeLink labs.

**Comment by dkampis** [comment]
it is unlikely that we have systematic differences in calibration. most likely this comes from the difference in screen size (CEU -  1200x900 size, Copenhagen 1280x960 size). 

we are looking into the position of the stimuli, as well as eye tracked (L/R, as eyelink only tracks one eye; though again, the latter is a bit unlikely to have caused this).
