### ISSUE TITLE
Outliers in Tobii

### ISSUE THREAD

**Issue by yuen-francis** [manybabies/mb2-analysis#31]
![image](https://user-images.githubusercontent.com/52611129/69903829-bea63b80-1353-11ea-9612-7cf3ae3b224d.png)
Tobii trackers seem to produce gaze coordinates that are outside the bounds of the screen, as shown in the image. Need to exclude these extremal values during import.R maybe?

**Comment by mcfrank** [comment]
Yes, I think clipping values outside of the screen size should probably be
something that happens in peekds if you want to approach it there?
