### ISSUE TITLE
Is pilot 1b CEU data misaligned in time?

### ISSUE THREAD

**Issue by mahowak** [manybabies/mb2-analysis#42]
-On a quick glance, it looks like the outcome condition of pilot 1b for CEU shows an earlier shift towards the target than others. Is there some misalignment somewhere?

**Comment by GalRaz** [comment]
I have been looking into this, though didn't find anything immediately. It seems to be consistent across the three participants, suggesting that there is a misalignment (s. screenshot). Could it have something to do with eyelink output starting 1s earlier (s. import.R for CEU)?
![Screen Shot 2020-04-04 at 8 10 22 PM](https://user-images.githubusercontent.com/17543199/78463902-b3bc3880-76b0-11ea-841b-1e04c405b3f1.png)

**Comment by angelinetsui** [comment]
@GalRaz , can you please use "facet" to see if there are difference between outcome condition and no_outcome condition? how many participants we can use in CEU pilot 1b? 3 or 4?

**Comment by GalRaz** [comment]
@angelinetsui  unfortunately the no_outcome condition is not very informative with this issue, because there is no clear point at which we would expect dramatic increase in looking to the target. We have 3 participants with 4 trials each for outcome + the same for no_outcome.

**Comment by mahowak** [comment]
@angelinetsui @GalRaz Yeah I can't find anything either. The bee swarm animation looks ok to me too: CEU seems to fall in line with the others. Actually @yuen-francis would data_integrity.Rmd help us here? Since you used that to identify the CEU left skew in Pilot 1a, maybe we could use that to see if there is a time misalignment here? (And to see if the left skew is fixed in this version?)

**Comment by yuen-francis** [comment]
@mahowak currently data_integrity.Rmd only detects positional misalignments, but I can take a look at it later in the week and see if I can add some features to detect time misalignments?

**Comment by mahowak** [comment]
@yuen-francis That sounds great.

**Comment by yuen-francis** [comment]
@mahowak haven't been able to come up with a way to detect time misalignment, but can confirm that the systematic difference between CEU and copenhagen still exists

![image](https://user-images.githubusercontent.com/52611129/79093817-49d40c80-7d0a-11ea-8e73-e4a430878f84.png)
