### ISSUE TITLE
fix subid

### ISSUE THREAD

**Issue by mahowak** [manybabies/mb2-analysis#46]
-subid is used throughout pilot_data_analysis.Rmd as if it is guaranteed to be unique but it is not guaranteed to be unique
-subid + lab + experiment_num would be unique

**Comment by angelinetsui** [comment]
got it, will fix it in the mixed-level analysis! Thanks very much for this

**Comment by angelinetsui** [comment]
fixed in the latest pull request (see the exclusion session)
