### ISSUE TITLE
Did something go wrong with exclusions?

### ISSUE THREAD

**Issue by GalRaz** [manybabies/mb2-analysis#50]
Just pulled the newest changes and after running exclusions, the sub_id column strangely adds the lab id too.
![Screen Shot 2020-04-07 at 1 16 54 AM](https://user-images.githubusercontent.com/17543199/78632775-e6f7f680-786d-11ea-9d68-4c735838c777.png)

**Comment by angelinetsui** [comment]
no, this is deliberate because of issue #46 . This issue has been noted in past MB studies and we need to ensure that all subid is unique for further analyses

**Comment by GalRaz** [comment]
ok.

**Comment by GalRaz** [comment]
It seems that the subid modification comes from this line:
`  mutate(subid = paste0(subid, sep = " _ ", lab, trial_num)) `

I think we should at remove the `trial_num` (did you mean to put trial_id?) from the subid column, because otherwise `group_by(subid)` starts treating each trial, rather than each subject, differently. We could add `experiment_num` to `subid` though.

**Comment by angelinetsui** [comment]
Got it, thanks for your explanation, may be we shouldn't make it too unique to avoid problems like that.....I honestly think that subid + lab is already unique enough to do the trick...perhaps just combining these two names. thoughts? @GalRaz @mahowak

**Comment by mahowak** [comment]
subid needs to uniquely identify each subject. 

subid + lab should usually do it, but because labs assign their own subid, they might call a particular subject mb2-1 in both Pilot 1a and Pilot 1b. 

What @GalRaz said sounds good: subid + lab + experiment_num should be unique

I am also a little thrown by having the sep arg right in the middle of the paste like that, how about: 

`mutate(subid = paste(subid, lab, experiment_num, sep="_"))`

**Comment by angelinetsui** [comment]
subid+lab+exp_num sounds good.

I can remove the sep arg, cause I don't think putting it at the end helps anything. I like putting it in the middle for me to see the original subid, but I am okay if you want to remove the sep 

Do you want me to change the codes, or @GalRaz?

**Comment by mahowak** [comment]
In paste sep is an arg that causes each part of the paste to be separated
by the sep character.

So paste(a, b, c, sep=‘_’) gives ‘a_b_c’

**Comment by angelinetsui** [comment]
sounds good to change it to paste()

**Comment by GalRaz** [comment]
just put in a pull request; closing

**Comment by mahowak** [comment]
Just to close the loop here, paste0 doesn't actually take a sep arg. It just concats all the args with no sep. But it lets you pass garbage names as arg names.

``> paste0("this", sillyarg="is", fakearg="a", dsfj9iw="test")
``
``
[1] "thisisatest"
``
