### ISSUE TITLE
AOIs: Top Left vs Bottom Left Origin, Video Resolution

### ISSUE THREAD

**Issue by adriansteffan** [manybabies/mb2-analysis#73]
Our current AOIs in generate_aois_for_primary_data.R assume a top left origin AND a 1200x900 stimulus video.

We need to recalculate our aoi coordinates to adhere to A) a bottom left origin and B) the 1280x960 resolution.

**Comment by adriansteffan** [comment]
The data integrity files of the pilot also assume a top left coordinate system, so if we want to reuse the code found there, we need to keep in mind to switch that

**Comment by alvinwmtan** [comment]
(Will be verified by heatmap etc.)
