### ISSUE TITLE
Double-check that familiarization trials are encoded in the correct order

### ISSUE THREAD

**Issue by mzettersten** [manybabies/mb2-analysis#84]
This is a reminder for us to make sure that trial number order is accurately reflected in the final data we analyze.

**Comment by adriansteffan** [comment]
Will double check, code should already do that

**Comment by adriansteffan** [comment]
In 003, we check that the order we assigned in the data matches the trial order as determined by the demographics file.
So unless the code is broken, we will catch any deviations there!
