### ISSUE TITLE
. instead of NA for missing XY data

### ISSUE THREAD

**Issue by mcfrank** [manybabies/mb2-analysis#88]
we see this issue in `babylingOslo_toddlers_xy_timepoints.csv`. @adriansteffan I think you imported this one.

**Comment by mcfrank** [comment]
I think this is handled OK but probably they should be turned into NAs at some point

**Comment by adriansteffan** [comment]
I got stuck on the eyelink data initially, so someone else did finish this one - maybe @alvinwmtan ? I also just checked `babylingOslo_toddlers_xy_timepoints.csv` and there are no "."s but the x/y coordinates does not change within each trial-participant pairing, so we should have another look in any case.

**Comment by alvinwmtan** [comment]
Fixed in 43ebff9227cc83eb30c24aeed998f37f1431f506
