### ISSUE TITLE
PKUSu has extra header rows

### ISSUE THREAD

**Issue by mcfrank** [manybabies/mb2-analysis#89]
In row 60727 of `PKUSu_adults_xy_timepoints.csv` we see an extra header row inserted mid-dataset . @yanwei-W I think you were looking at this one, can you take a look? thanks!

**Comment by mcfrank** [comment]
again I think they are just getting forced to NAs but that's just a side effect of the particular `read_csv` parser, it's not a guarantee so we should probably resolve this.

**Comment by yanwei-W** [comment]
Sure! I found that the raw data files of PKUSu (both toddlers and adults) had extra header rows. It seemed there was something wrong when we combined each participant's file into one file. I have resolved it and re-uploaded the PKUSu_adults_xy_timepoints.csv and PKUSu_toddlers_xy_timepoints.csv @mcfrank

**Comment by mcfrank** [comment]
thank you!
Mike
