### ISSUE TITLE
unusual first trial length for a handful of participants

### ISSUE THREAD

**Issue by mzettersten** [manybabies/mb2-analysis#91]
A few participants have surprisingly long first trials (based on media file name) and should be double-checked:

- [x] MARCS_24
- [x] MARCS_28
- [x] 2116AlYa

**Comment by lucie-zimmer** [comment]
The lab that tested MARCS_24 and MARCS_28 cannot recall anything unusual during the testings of these two. I also checked, if it is an issue of a specific media file: the mediafile in the first test trial was the same for MARCS_24 and MARCS_28 (KNOW_RL), but different for 2116AlYa (NEW_KNOW_LL). Another commonality is that they were all tested using Tobii Studio.

I assume it is a technical issue and we need to exclude them. What do you think?

**Comment by lucie-zimmer** [comment]
I updated the demo data of WSUMARCS_adult (IDs: MARCS_24 & MARCS_28) and careylabHarvard_adults (ID: 2116AlYa) on OSF accordingly (i.e., session error, 4 (=technical error).
