### ISSUE TITLE
Wait for labs to get back to us

### ISSUE THREAD

**Issue by adriansteffan** [manybabies/mb2-analysis#93]
- [x]  WSUMARCS_adults_participantdata.csv has duplicated columns with different values - so probably want to reduce to just the columns with the correct values:
second_session
session_error_notes

- [x] babylabNijmegen 
adult: why is RU_022 missing?
baby: why are RU_016, RU_023 missing?

**Comment by lucie-zimmer** [comment]
babylabNijmegen sent us the missing data files. The data can be found here: https://drive.google.com/drive/u/0/folders/1-vT1ibGKJna2jXxTzFmFRa78uPEXiWVf

**Comment by lucie-zimmer** [comment]
the demo data file of WSUMARCS is also updated on OSF and GoogleDrive

**Comment by adriansteffan** [comment]
> babylabNijmegen sent us the missing data files. The data can be found here: https://drive.google.com/drive/u/0/folders/1-vT1ibGKJna2jXxTzFmFRa78uPEXiWVf

@yanwei-W could you have a look at this?

**Comment by yanwei-W** [comment]
> > babylabNijmegen sent us the missing data files. The data can be found here: https://drive.google.com/drive/u/0/folders/1-vT1ibGKJna2jXxTzFmFRa78uPEXiWVf
> 
> @yanwei-W could you have a look at this?

Sure！

**Comment by yanwei-W** [comment]
I have added the new data into the files and uploaded them to OSF.

**Comment by adriansteffan** [comment]
> I have added the new data into the files and uploaded them to OSF. @adriansteffan

Thanks for that, we nearly fixed all ID mismatches now! It seems that RU_016 is still missing from the toddler eyetracking data on OSF. Could you take another look at that?

**Comment by lucie-zimmer** [comment]
@yanwei-W : could you please check the eye-tracking data of babylabNijmegen_toddlers that are saved on OSF again and add the data of RU_016? The lab sent us the missing tsv-file of RU_016 which can be found here https://drive.google.com/drive/u/0/folders/1-vT1ibGKJna2jXxTzFmFRa78uPEXiWVf

**Comment by yanwei-W** [comment]
OK, I'm working on it.

**Comment by yanwei-W** [comment]
I find out the problem. It seems that the lab recorded ParticipantName of RU_016 as "RU_017". I will fix it and upload again.
