### ISSUE TITLE
Fix ID Mismatches

### ISSUE THREAD

**Issue by adriansteffan** [manybabies/mb2-analysis#94]
- [x] Next thing: Check the situation on id mismatches after renamings and new data

**Comment by adriansteffan** [comment]
Include a list to ignore all participants that are missing in the ET data due to technical failures - they should not make the validation fail

**Comment by adriansteffan** [comment]
ADULT_006 from beinghumanWroclaw needs to be ignored in the ET data

**Comment by adriansteffan** [comment]
gertlabLancaster, Renaming: The IDs in the demo file have a preceding "LU_" that the IDs in the ET file do not have. 
LU_3746 -> 3746

**Comment by adriansteffan** [comment]
- [ ] Fix the leftover issues for the Adult cohort

These IDs appear in the demo data but are not found in the ET data:

babylabNijmegen | RU_022 (should be automatically fixed once Yanwei completes the import and uploads to osf)
gaugGöttingen | GAUG_124
gaugGöttingen | GAUG_130
kidsdevUniofNewcastle | uon017
kidsdevUniofNewcastle | uon018
UIUCinfantlab | NR

These IDs appear in the ET files but not the demographics:

childdevlabAshoka | 33-49 are missing from the demo file
PKSu | 101-142 are missing from the demo file

@Lucie (still not in the repo 👀 ) Could you have a look?

**Comment by adriansteffan** [comment]
- [ ]  Fix the leftover issues for the toddler cohort
These IDs appear in the demo data but are not found in the ET data:

babylabNijmegen | RU_016-toddlers (Yanwei is on it)
babylabNijmegen | RU_023-toddlers (Yanwei is on it)
beinghumanWroclaw | BABY_026-toddlers
gertlabLancaster | LU_3955-toddlers
irlConcordia | S004_NK-toddlers
irlConcordia | S010_NK-toddlers
irlConcordia | S016_NK-toddlers

@lucie-zimmer Could you have a look?

**Comment by lucie-zimmer** [comment]
first part:
