### ISSUE TITLE
UoO231 was assigned twice by oxfordBabylab

### ISSUE THREAD

**Issue by adriansteffan** [manybabies/mb2-analysis#98]
participant_id == 'UoO231' && lab_id == 'oxfordBabylab' 

This participant appears twice in the eyetracking data and the demographic data - they assigned the same id to two participants.
One of them saw trial order 4 and the other one trial order 27.

It might make the most sense to fix this in the imports, as the unique id assumption gets relevant quite early in the pipeline e.g. at the resampling stage. So one of the two participants would need to be renamed in the demographic file manually, while the import script picks the corresponding appearance of the id in the raw ET data and renames it.

**Comment by yanwei-W** [comment]
I have added new data of UoO611 and changed the second "UoO231" (trial order 27) to "UoO232" in the new data  @file. However, I don't have the permission to upload the new data file in the seperate oxford google file (https://drive.google.com/open?id=10rXhDUFw72ddDDNyu7EUaG0uGBjrJvFe&usp=drive_fs). @adriansteffan
